name: edm-H100
channels:
  - pytorch
  - nvidia
dependencies:
  - python>=3.8, < 3.10  # package build failures on 3.10 (edm)
  - pip
  - numpy>=1.21, <2.0 # need a good version
  - click>=8.0
  - pillow>=8.3.1
  - scipy>=1.7.1
  - pytorch=1.13.1 # need a version that supports H100
  - psutil
  - requests
  - tqdm
  - imageio
  - pip:
    - imageio-ffmpeg>=0.4.3
    - pyspng
